title: Document REST APIs
subtitle: A guide for technical writers
sidebar: docapis

language: english
target: print

destination: _site
port: 4000
highlighter: rouge
exclude:
  - mobi
  - pdf
target: pdf

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: printpdf
  -
    scope:
      path: ""
      type: docs
    values:
      layout: printpdf
