title: Document REST APIs
language: english
target: web
sidebar: docapis

# Link to home
url: http://idratherbewriting.com/learnapidoc

destination: _site
port: 4000
highlighter: rouge
exclude:
  - mobi
  - pdf
target: web

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true
  search:
    output: true

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      topnav: topnav
  -
    scope:
      path: ""
      type: docs
    values:
      layout: default
      topnav: topnav
  -
    scope:
      path: ""
      type: search
    values:
      layout: default
      topnav: topnav
      type: search
  -
    scope:
      path: "images"
    values:
      image: true


########## UI text ###############

google_analytics:
disqus_shortname: idratherbewriting
google_analytics: UA-408430-5

uistring:
    tableofcontents: Table of Contents
    log_doc_issue: Log Doc Issue
    breadcrumb:
      home: Home
      documentation: Documentation
    expandall: Expand All
    collapseall: Collapse All
    title: Learn API Doc # Displays as site title on top nav bar and on site metadata
    description: A guide for technical writers learning how to document APIs  # Displays as site description meta
    search_placeholder_product: Search ...
    github_edit_button_text: Edit on GitHub
    search_results_page_title: Search results
    search_no_results_found: No results found.
    products: Products
    docindex_product: Product
    docindex_startpage: Starting page
