language: english
target: print

destination: _site
port: 4000
highlighter: rouge
exclude:
  - mobi
  - pdf
target: pdf

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: printpdf
      topnav: topnav
  -
    scope:
      path: ""
      type: docs
    values:
      layout: printpdf
      topnav: topnav
  -
    scope:
      path: images
    values:
      image: true


########## UI text ###############


uistring:
    tableofcontents: Table of Contents
    log_doc_issue: Log Doc Issue
