title: Documenting REST APIs
media: https://idratherbewritingmedia.com/
language: english
sidebar: docapis

# Link to home
url: https://idratherbewriting.com
baseurl: /learnapidoc

destination: _site
port: 4000
highlighter: rouge
exclude:
  - mobi
  - pdf
format: web

plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      topnav: topnav
  -
    scope:
      path: ""
      type: docs
    values:
      layout: default
      topnav: topnav
      progress: true
  -
    scope:
      path: "images"
    values:
      image: true

plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate

########## UI text ###############

disqus_shortname: idratherbewriting

uistring:
    tableofcontents: Table of Contents
    log_doc_issue: Log Doc Issue
    breadcrumb:
      home: Home
      documentation: Documentation
    expandall: Expand All
    collapseall: Collapse All
    title: Learn API Doc # Displays as site title on top nav bar and on site metadata
    description: A guide for technical writers and engineers learning how to document APIs  # Displays as site description meta
    github_edit_button_text: Edit on GitHub
    products: Products
    docindex_product: Product
    docindex_startpage: Starting page


####### Algolia configuration ###########
algolia:
  application_id: 7JEKBAXL1Y
  index_name: learnapidocs
  search_only_api_key: 268324bcfa734077d7983ed51a671760
  files_to_exclude:
    - ./toc.html
    - _docs/pdf_frontmatter/*
    - _docs/introduction_to_rest_apis/tocstart.html
    - _docs/introduction_to_rest_apis/tocstart_fulldetails.md
